-- Create 3 Table mahasiswa,dosen,mata_kuliah : 
-- JAWABAN NOMOR_1

CREATE TABLE mahasiswa(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nim BIGINT,
	nama VARCHAR(100),
	tgl_lhr DATE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT nim_unik UNIQUE(nim)
);

CREATE TABLE dosen(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	kd_dosen BIGINT,
	nama VARCHAR(100),
	email VARCHAR(100),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT email_unik UNIQUE(email)
);

CREATE TABLE mata_kuliah(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	matkul VARCHAR(100),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

